### ISSUE TITLE
Finalize data schema, not including user data

### ISSUE THREAD

**Issue by sonyccd** [sonyccd/hermes-firebase#8]
This really needs to be done in the next week or so. It is blocking almost everything.  User data schema will be taken care of by firebase.

**Comment by sonyccd** [comment]
This covers some of the pros and cons to how we lay the data out.
https://firebase.google.com/docs/firestore/manage-data/structure-data

**Comment by brendanwalters** [comment]
- (User)
- Sensor
  - ID
- Dive
  - ID, GPS start, GPS end, data count, time start, time end
  - Data
    - Time, Depth, Temp1, Temp2

**Comment by sonyccd** [comment]
``` 
let dive = {
    sensorId: sensorId,
    version: rawData[0],
    coordinateStart: new admin.firestore.GeoPoint(diveData[0], diveData[1]),
    coordinateEnd: new admin.firestore.GeoPoint(diveData[2], diveData[3]),
    dataCount: diveData[4],
    timeStart: new Date(diveData[5]),
    timeEnd: new Date(diveData[6])
  };
```
